conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('', views.items, name='items')
]

online_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        # 'placeholder': 'Your Username',
        'class': 'form-field'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder': 'Your Password',
        'class': 'form-field'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        # 'placeholder': 'Your Username',
        'class': 'form-field'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        # 'placeholder': 'Your Email address',
        'class': 'form-field'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder': 'Your Password',
        'class': 'form-field'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder': 'Repeat Password',
        'class': 'form-field'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from item.models import Category, Item

from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[:8]
    categories = Category.objects.all()[:4]
    
    context = {
        'items': items,
        'categories': categories
    }
    
    return render(request, 'core/index.html', context)


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login')
        
    else:    
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })
    
    
def logout_view(request):
    logout(request)
    return redirect('core:index')

core/templates/core/contact.html
{% extends 'core/layout.html' %}

{% block title %}
    Contact
{% endblock %}


{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/layout.html' %}

{% block title %}
    Home Page
{% endblock %}


{% block content %}
    <div class="items-container">
        <p class="container-title">Newest Items</p>

        <div class="items-grid">
            {% for item in items %}
            <div class="item-card">
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img class="item-image" src="{{ item.image.url }}" alt="">
                    </div>

                    <div class="item-description">
                        <p class="item-name">{{ item.name }}</p>
                        <p class="item-price">Price: {{ item.price }} $</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="items-container">
        <p class="container-title">Categories</p>

        <div class="items-grid">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                        <div class="categories-card">
                            <p class="category-name">{{ category.name }}</p>
                            <p class="category-count">
                                {% if category.items.count == 1 %}
                                    1 item
                                {% else %}
                                    {{ category.items.count }} items
                                {% endif %}
                                </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'core/styles.css' %}">
        <link rel="stylesheet" href="{% static 'core/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/index.css' %}">
        <link rel="stylesheet" href="{% static 'core/detail.css' %}">
        <link rel="stylesheet" href="{% static 'core/signup_login.css' %}">
        <link rel="stylesheet" href="{% static 'core/newitem.css' %}">
        <link rel="stylesheet" href="{% static 'core/conversation.css' %}">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet">


        <title>
            {% block title %}
            {% endblock %} | Thunder Marketplace
        </title>
    </head>

    <body>
        <nav class="upper-nav">
            <a href="/" class="thunder-title">THUNDER</a>

            <div class="right-side-nav-elems">
                <a href="{% url 'item:new' %}" class="right-side-elem browse-new-item">New item</a>
                <a href="{% url 'item:items' %}" class="right-side-elem browse-new-item">Browse</a>

                {% if request.user.is_authenticated %}

                    <a href="{% url 'conversation:inbox' %}" id="inbox-button" class="right-side-elem upper-right-btns">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" id="dashboard-button" class="right-side-elem upper-right-btns ">Dashboard</a>

                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="logout-btn" type="submit">Logout</button>
                    </form>
                {% else %}
                    <a href="{% url 'core:signup' %}" id="sign-up-button" class="right-side-elem upper-right-btns">Sign Up</a>
                    <a href="{% url 'core:login' %}" id="log-in-button" class="right-side-elem upper-right-btns ">Log In</a>
                {% endif %}
            </div>
        </nav>

        <div class="main-content">
            {% block content %}
            {% endblock %}
        </div>

        <footer id="footer-id">
            <div class="">
                <h4 class="">About</h4>
                
                <p class="footer-about-description">Information about the website to be displayed right here in this section.</p>
            </div>
            
            <div class=" footer-menu">
                <h3>Menu</h3>
                <ul class="ul-footer">
                    <li><a href="#" class="">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="">Contact</a></li>
                    <li><a href="#" class="">Privacy Policy</a></li>
                    <li><a href="#" class="">Terms of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/login.html
{% extends 'core/layout.html' %}

{% block title %}
    Sign up
{% endblock %}

{% block content %}
    <div class="form-container">
        <div class="form-body" id="login-form-body">
            <p class="form-title">Log In</p>

            <form action="." method="POST">
                {% csrf_token %}

                <div class="form-row">
                    <label for="username">Username:</label>
                    {{ form.username }}
                </div>

                <div class="form-row">
                    <label for="password">Password:</label>
                    {{ form.password }}
                </div>

                {% if form.errors or form.non_field_error %}
                    <div class="errors-field">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <button type="submit" id="login-button" class="signup-login-button">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/layout.html' %}

{% block title %}
    Sign up
{% endblock %}

{% block content %}
    <div class="form-container">
        <div class="form-body">
            <p class="form-title">Sign Up</p>

            <form action="." method="POST">
                {% csrf_token %}

                <div class="form-row">
                    <label for="username">Username:</label>
                    {{ form.username }}
                </div>

                <div class="form-row">
                    <label for="email">Email:</label>
                    {{ form.email }}
                </div>

                <div class="form-row">
                    <label for="password1">Password:</label>
                    {{ form.password1 }}
                </div>

                <div class="form-row">
                    <label for="password2">Confirm Password:</label>
                    {{ form.password2 }}
                </div>

                {% if form.errors or form.non_field_error %}
                    <div class="errors-field">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <button type="submit" class="signup-login-button">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}