conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('', views.items, name='items')
]

online_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.name
    
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images')
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("category", "name", "description", "price", "image")
        
        widgets = {
            'category': forms.Select(attrs={
                'class': 'newitem-field'
            }),
            
            'name': forms.TextInput(attrs={
                'class': 'newitem-field'
            }),
            
            'description': forms.Textarea(attrs={
                'class': 'newitem-field'
            }),
            
            'price': forms.TextInput(attrs={
                'class': 'newitem-field'
            }),
            
            'image': forms.FileInput(attrs={
                'class': 'newitem-field',
                'id': 'newitem-image-field'
            }),
        }
        

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("name", "description", "price", "image", "is_sold")
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'newitem-field'
            }),
            
            'description': forms.Textarea(attrs={
                'class': 'newitem-field'
            }),
            
            'price': forms.TextInput(attrs={
                'class': 'newitem-field'
            }),
            
            'image': forms.FileInput(attrs={
                'class': 'newitem-field',
                'id': 'newitem-image-field'
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .models import Category, Item
from .forms import NewItemForm, EditItemForm


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    
    if category_id:
        items = items.filter(category_id=category_id)
    
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })




# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:3]
    
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })
    
    
@login_required
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            
            return redirect('item:detail', pk=item.id)
        
    else:
        form = NewItemForm()
    
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })
    

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
        
    else:
        form = EditItemForm(instance=item)
    
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })
    
    
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    
    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/layout.html' %}

{% block title %}
    {{ item.name }}
{% endblock %}

{% block content %}
    <div class="detail-container">

            <img src="{{ item.image.url }}" class="detail-image-item" alt="">

        <div class="detail-details">
            <p id="detail-item-title">{{ item.name }}</p>
            <p class=""><strong>Price: </strong>{{ item.price }} $</p>
            <p class=""><strong>Seller: </strong>{{ item.created_by.username }}</p>

            {% if item.description %}
            <p class=""><strong>Description:</strong>
                <br>
                {{ item.description }}
            </p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="edit-delete-container">
                    <p class="own-ph">You own this item</p>

                    <a id="own-edit-btn" class="own-btn" href="{% url 'item:edit' item.id %}">Edit</a>
                    <a id="own-delete-btn" class="own-btn" href="{% url 'item:delete' item.id %}">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'conversation:new' item.id %}" style="color: white">
                    <div class="contact-seller-button">
                        Contact Seller
                    </div>
                </a>
            {% endif %}
        </div>
    </div>

    <div class="items-container" id="related-items-container">
        <p class="container-title">Related Items</p>

        {% if related_items %}
        <div class="items-grid">
            {% for item in related_items %}
            <div class="item-card">
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img class="item-image" src="{{ item.image.url }}" alt="">
                    </div>

                    <div class="item-description">
                        <p class="item-name">{{ item.name }}</p>
                        <p class="item-price">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        {% else %}
            <p>No related items...</p>
        {% endif %}
    </div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/layout.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    <p class="newitem-title">{{ title }}</p>

    <div class="newitem-form-container">
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-row newitem-form-row">
                <label for="category">Category: </label>
                {{ form.category }}
            </div>

            <div class="form-row newitem-form-row">
                <label for="name">Name: </label>
                {{ form.name }}
            </div>

            <div class="form-row newitem-form-row">
                <label for="description">Description: </label>
                {{ form.description }}
            </div>

            <div class="form-row newitem-form-row">
                <label for="price">Price: </label>
                {{ form.price }}
            </div>

            <div class="form-row newitem-form-row">
                <label for="image">Image: </label>
                {{ form.image }}
            </div>

            {% if form.errors or form.non_field_error %}
                <div class="errors-field">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="newitem-button">Submit</button>
        </form>

    </div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/layout.html' %}

{% block title %}
    Browse
{% endblock %}

{% block content %}
    <div class="browse-main">
        <div class="browse-sidebar">
            <form action="{% url 'item:items' %}" method="GET">
                <input type="text" name="query" class="browse-input" value="{{ query }}" placeholder="Find items...">

                <button type="submit" class="search-btn">Search</button>
            </form>


            <p class="ctgrs">Categories</p>

            <ul style="
            list-style-type: none;
            margin-bottom: 50px;">
                {% for category in categories %}
                <li class="unfocused-category{% if category.id == category_id %} focused-category {% endif %}">
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                        {% if category.id == category_id %}
                            > {{ category.name }}
                        {% else %}
                            {{ category.name }}
                        {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>



            <a href="{% url 'item:items' %}" class="clear-btn">Clear Filters</a>
        </div>

        <div class="items-container" id="browse-container">
            <div class="items-grid" id="browse-grid">
                {% for item in items %}
                <div class="item-card">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img class="item-image" src="{{ item.image.url }}" alt="">
                        </div>
    
                        <div class="item-description">
                            <p class="item-name">{{ item.name }}</p>
                            <p class="item-price">Price: {{ item.price }} $</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}